export const NEXT_PUBLIC_APIKEY =
  process.env.NEXT_PUBLIC_APIKEY || "AIzaSyCtIFqAjhJaT1jBhf7Ofg6lf7ZGSRGuHpQ";
export const NEXT_PUBLIC_AUTH_DOMAIN =
  process.env.NEXT_PUBLIC_AUTH_DOMAIN || "profile-me-dab9a.firebaseapp.com";
export const NEXT_PUBLIC_PROJECT_ID =
  process.env.NEXT_PUBLIC_PROJECT_ID || "profile-me-dab9a";
export const NEXT_PUBLIC_STORAGE_BUCKET =
  process.env.NEXT_PUBLIC_STORAGE_BUCKET || "profile-me-dab9a.appspot.com";
export const NEXT_PUBLIC_MESSAGIN_SENDER_ID =
  process.env.NEXT_PUBLIC_MESSAGIN_SENDER_ID || "420603135304";
export const NEXT_PUBLIC_APP_ID =
  process.env.NEXT_PUBLIC_APP_ID || "1:420603135304:web:b479850c5e1e7599455f7d";
export const NEXT_PUBLIC_MEASUREMENT_ID =
  process.env.NEXT_PUBLIC_MEASUREMENT_ID || "G-RKXLG8H51C";

export const NEXT_PUBLIC_COLLECT_WORKED =
  process.env.NEXT_PUBLIC_COLLECT_WORKED || "worked";
export const NEXT_PUBLIC_COLLECT_SKILLS =
  process.env.NEXT_PUBLIC_COLLECT_SKILLS || "skills";
export const NEXT_PUBLIC_COLLECT_EDUCATION =
  process.env.NEXT_PUBLIC_COLLECT_EDUCATION || "education";
export const NEXT_PUBLIC_COLLECT_LANGUAGES =
  process.env.NEXT_PUBLIC_COLLECT_LANGUAGES || "languages";
export const NEXT_PUBLIC_COLLECT_INTERESTS =
  process.env.NEXT_PUBLIC_COLLECT_INTERESTS || "interests";

export const API_COLLECT = [
  NEXT_PUBLIC_COLLECT_WORKED,
  NEXT_PUBLIC_COLLECT_SKILLS,
  NEXT_PUBLIC_COLLECT_EDUCATION,
  NEXT_PUBLIC_COLLECT_LANGUAGES,
  NEXT_PUBLIC_COLLECT_INTERESTS,
];
